### PR TITLE
Gradle example for multimodule library

### PR DESCRIPTION
**Pull request by skjolber**
Additional gradle build example - a multi-module library which includes examples.

### CODE REVIEW

**Comment by skjolber** [comment]
@yahavi @eyalbe4 @arielkv any hope for review?

**Comment by eyalbe4** [comment]
Sure @skjolber,
Give us a few more days. Thanks!

**Comment by eyalbe4** [comment]
@skjolber,
While we're reviewing your addition, can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your example?

**Comment by eyalbe4** [comment]
@skjolber,
First of all, thanks for contributing this example. The example looks good, but I'm not sure its focus is the Artifactory Plugin for Gradle. It uses the plugin of course, but this repository is aimed at providing a few quick startup examples for using the plugin.

**Pull request closed without merging**
