### PR TITLE
Android Sample

### PR DESCRIPTION
**Pull request by hannesa2**
This is a showcase of https://github.com/jfrog/artifactory-client-java/issues/362 
image

`Using in Android causes a "No static field"`

Please push the only button you and you will run into [this crash](https://github.com/jfrog/project-examples/pull/343/files#diff-260b3c2147e9836a7985e2d60c45b9ea112267dcc31a015e14452aa8cdc0861cR27)
```
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
        at org.jfrog.artifactory.client.httpClient.http.HttpBuilderBase.createConnectionMgr(HttpBuilderBase.java:359)
        at org.jfrog.artifactory.client.httpClient.http.HttpBuilderBase.configConnectionManager(HttpBuilderBase.java:344)
        at org.jfrog.artifactory.client.httpClient.http.HttpBuilderBase.build(HttpBuilderBase.java:78)
        at org.jfrog.artifactory.client.ArtifactoryClientBuilder.createClientBuilder(ArtifactoryClientBuilder.java:174)
        at org.jfrog.artifactory.client.ArtifactoryClientBuilder.build(ArtifactoryClientBuilder.java:196)
        at org.jfrog.example.jfrogandroid.JFrogHelper.requestArtifactoryVersions(JFrogHelper.kt:27)
        at org.jfrog.example.jfrogandroid.JFrogHelper$checkArtifactoryDialog$1.invokeSuspend(JFrogHelper.kt:19)
```

The also interesting part is, that it works with the provided [unit test](https://github.com/jfrog/project-examples/pull/343/files#diff-7d75b8625f4898dee7ad9db291ddcd1ccd22353f7148418b246de900608fc52dR18-R23)

### CODE REVIEW

**Comment by hannesa2** [comment]
@yahavi @eyalbe4 Can you reproduce the issue now ?

**Comment by hannesa2** [comment]
In version `2.13.1` the error still exists

**Comment by eyalbe4** [comment]
@hannesa2,
I think we can have this PR closed, because there's actually no need to have a PR open for reproducing the issue.
We can continue communicating here about the issue if it is still relevant.

**Comment by hannesa2** [comment]
Sure, it's still relevant !

1. This demonstration helps you to see the issue
2. After demonstration you can fix it and see in pipeline the solution

I put afford into it, and you only close and never investigated. This is a sign !

**Pull request closed without merging**
