### PR TITLE
Add a minimal README for the maven example, that is still missing bits

### PR DESCRIPTION
**Pull request by areese**

### CODE REVIEW

**Comment by eyalbe4** [comment]
@areese, this *maven-example* project actually does not use the *Maven Artifactory Plugin*, but is a standard maven project, that is used as a sample project, that can resolve dependencies, deploy artifacts and publish build-info from a CI server using the Jenkins, TeamCity and Bamboo Artifactory Plugins.

**Comment by areese** [comment]
@eyalbe4 Ok, I'm going to restructure it then so it looks like the gradle examples and point this out in the read me.

It wasn't clear to me what this was for, and I needed a example of how to publish using the artifactory plugin.

:)

**Comment by areese** [comment]
@eyalbe4 I've tried to restructure this a little to have a pull and publish example, we can talk more at SwampUp.  :)

**Comment by areese** [comment]
Another shot at moving things around to have better structure.
We'll have to read the docs and if you agree this is a good layout we can figure out what is missing.  :)

**Comment by eyalbe4** [comment]
@areese,
Do you think this pull request is still relevant? It's been open for a long time. My apologies for this.
Maybe we can split if into smaller chunks and get them merged one by one?

**Comment by eyalbe4** [comment]
@areese,
I'm closing this one for now.

**Pull request closed without merging**
